version: '3'

tasks:
  default:
    cmds:
      - pio run --target upload --target monitor --environment m5stack-atoms3r

  convert:
    dir: ./src/speak/assets/
    cmds:
      - rm -rf *.h
      - |
        for f in *.wav; do
          xxd -i "$f" > "${f%.wav}.h";
        done
      - sd 'unsigned char' 'EXT_RAM_ATTR const unsigned char' *.h

  format:
    cmds:
      - clang-format -i src/*.{cpp,h} -i src/**/*.{cpp,h}
