version: '3'

tasks:
  default:
    cmds:
      - pio run --target upload --environment m5stack-atoms3r

  convert:
    dir: ./src/player/assets/
    cmds:
      - rm -rf *.hpp
      - |
        for f in *.wav; do
          xxd -i "$f" > "${f%.wav}.hpp";
        done
      - sd 'unsigned char' 'EXT_RAM_ATTR const unsigned char' *.hpp

  format:
    cmds:
      - clang-format -i src/*.{cpp,hpp} -i src/**/*.{cpp,hpp}
