trigger:
- main

pool:
  vmImage: 'windows-latest'
  # vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'
# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

variables:
- group: 'testvargroup'
  # azureSubscription: '<サービス接続名>'
  # webAppName: '<App Service名>'

steps:
- task: ArchiveFiles@2
  displayName: 'Zip HTML files'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/site.zip'

- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)/site.zip'
