version: "3"

tasks:
  build:
    cmds:
      - clang++ -std=c++17 -Wall -Wextra $(pkg-config --cflags fmt) -o fmt_try main.cpp $(pkg-config --libs fmt)

  run:
    deps: [build]
    cmds:
      - ./fmt_try
