version: 2

# sources:
#   - name: app
#     schema: public
#     tables:
#       - name: users
#       - name: tasks
#       - name: tags
#       - name: task_tags

models:
  - name: users
    description: User data
    columns:
      - name: id
        description: User ID
      - name: name
        description: User name
      - name: email
        description: User email
      - name: created_at
        description: User created_at

  - name: tasks
    description: Task data
    columns:
      - name: id
        description: Task ID
      - name: user_id
        description: User ID
      - name: title
        description: Task title
      - name: status
        description: Task status
      - name: due_date
        description: Task due date
      - name: created_at
        description: Task created_at

  - name: tags
    description: Tags data
    columns:
      - name: id
        description: Tag ID
      - name: user_id
        description: User ID
      - name: name
        description: Tag name

  - name: task_tags
    description: Task tags data
    columns:
      - name: task_id
        description: Task ID
      - name: tag_id
        description: Tag ID
