version: 2

models:
  - name: users
    description: "User information"
    columns:
      - name: id
        description: "Primary key of the user"
        tests:
          - unique
          - not_null
      - name: name
        description: "User's name"
        tests:
          - not_null
      - name: email
        description: "User's email address"
        tests:
          - unique
          - not_null
      - name: created_at
        description: "Timestamp when the user was created"

  - name: tasks
    description: "Tasks assigned to users"
    columns:
      - name: id
        description: "Primary key of the task"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Foreign key to users"
        tests:
          - not_null
      - name: title
        description: "Title of the task"
        tests:
          - not_null
      - name: status
        description: "Task status (pending/done/etc.)"
        tests:
          - not_null
      - name: due_date
        description: "Task due date"
      - name: created_at
        description: "Timestamp when the task was created"

  - name: tags
    description: "Tags that users can assign to tasks"
    columns:
      - name: id
        description: "Primary key of the tag"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Foreign key to users"
        tests:
          - not_null
      - name: name
        description: "Tag name"
        tests:
          - not_null

  - name: task_tags
    description: "Many-to-many relation between tasks and tags"
    columns:
      - name: task_id
        description: "Foreign key to tasks"
        tests:
          - not_null
      - name: tag_id
        description: "Foreign key to tags"
        tests:
          - not_null
