services:
  drupal:
    image: drupal:11-apache
    ports:
      - 8080:80
    volumes:
      - ./drupal:/opt/drupal/web/sites/default/files
    depends_on:
      - db

  db:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: