import pyttsx3
from pprint import pprint

# generated by chatgpt
text = """
イタリアには数多くの魅力的な観光名所があります。

まずローマにあるコロッセオは、古代ローマ時代に建てられた巨大な円形闘技場で、剣闘士の試合や公開娯楽が行われていました。
現在でもローマ帝国の権力や高度な建築技術を感じられる象徴的な遺跡です。

次にヴェネツィアの中心に広がるサン・マルコ広場は、「世界で最も美しい広場」とも称され、サン・マルコ大聖堂や鐘楼に囲まれた優雅な空間が特徴です。
水の都ならではの雰囲気を楽しめる場所として多くの人を魅了しています。

さらにピサにあるピサの斜塔は、建設途中の地盤沈下によって傾いたことで有名な鐘楼で、
白い大理石の美しい外観と独特の傾きが世界中の観光客を引きつけています。
"""

text_en = """
Italy is home to many famous tourist attractions. 

First, the Colosseum in Rome is a massive amphitheater built in ancient Roman times, where gladiatorial contests and public spectacles were once held. 
Even today, it stands as a powerful symbol of the Roman Empire’s strength and advanced architectural skills. 

Next, St. Mark’s Square in Venice is often described as one of the most beautiful squares in the world, surrounded by landmarks such as St. Mark’s Basilica and its bell tower, creating an elegant atmosphere unique to the city of canals. 

Finally, the Leaning Tower of Pisa is a well-known bell tower that became tilted due to ground subsidence during construction, and its white marble exterior and distinctive lean continue to attract visitors from around the globe.
"""

engine = pyttsx3.init()

# speak japanese
engine.say(text)
engine.runAndWait()

# list supported voices (languages)
voices = engine.getProperty('voices')
for voice in voices: # type: ignore
    pprint(voice.id)
    # 'com.apple.speech.synthesis.voice.Albert'
    # 'com.apple.voice.compact.it-IT.Alice'
    # 'com.apple.voice.compact.kn-IN.Alpana'
    # 'com.apple.voice.compact.sv-SE.Alva'
    # 'com.apple.voice.Aman'
    # 'com.apple.voice.compact.fr-CA.Amelie'
    # 'com.apple.voice.compact.ms-MY.Amira'
    # 'com.apple.voice.compact.de-DE.Anna'

engine = pyttsx3.init()
engine.setProperty('voice', 'com.apple.eloquence.en-US.Shelley')
engine.say(text_en)
engine.runAndWait()
