
### これは ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  NGINX_ENV: production2

---

### これは Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: NGINX_ENV
              valueFrom:
                configMapKeyRef:
                  name: nginx-config   ### ここで参照してる
                  key: NGINX_ENV

---
### これは service
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
