name: jaffle_shop
version: '1.0.0'

profile: jaffle_shop

# paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# directories to be removed by `dbt clean`
clean-targets:
  - target
  - dbt_packages

# models
# see https://docs.getdbt.com/docs/configuring-models
models:
  jaffle_shop:
    +materialized: table
