# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

controllers:
    resource: routing.controllers

# see https://symfony.com/bundles/NelmioApiDocBundle/current/index.html
# app.swagger:
#     path: /api/doc.json
#     controller: nelmio_api_doc.controller.swagger
app.swagger_ui:
    path: /
    controller: nelmio_api_doc.controller.swagger_ui
app.redocly:
    path: /redocly
    defaults: { _controller: nelmio_api_doc.controller.redocly }
app.stoplight:
    path: /stoplight
    defaults: { _controller: nelmio_api_doc.controller.stoplight }
app.scalar:
    path: /scalar
    defaults: { _controller: nelmio_api_doc.controller.scalar }
